# Generated by Django 5.0 on 2024-01-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(max_length=255)),
                ('allergy_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('allergic_reaction', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diagnosis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_fname', models.CharField(max_length=255)),
                ('doctor_lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('doctor_contact_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('license_no', models.BigIntegerField()),
                ('specialty', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('test_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('vitalsign_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vitalsign',
            },
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('blood_press_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
                ('blood_press', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'blood_pressure',
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('heart_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetaken', models.DateField()),
                ('heart_rate', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'heart_rate',
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('immu_id', models.AutoField(primary_key=True, serialize=False)),
                ('immu_name', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'immunizations',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medications_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_date', models.DateField()),
                ('medications', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=255)),
                ('report_file', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='RespirationRate',
            fields=[
                ('resp_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetaken', models.DateField()),
                ('resp_rate', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'respiration_rate',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('surgeon', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'surgery',
            },
        ),
        migrations.CreateModel(
            name='TestAppointment',
            fields=[
                ('test_appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.test')),
            ],
            options={
                'db_table': 'test_appointment',
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('test_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_report_date', models.DateField()),
                ('test_report_file', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.doctor')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
                ('test_type', models.ForeignKey(db_column='test_type_id', on_delete=django.db.models.deletion.CASCADE, to='cureme.test')),
            ],
            options={
                'db_table': 'test_report',
            },
        ),
    ]
