# Generated by Django 5.0 on 2024-01-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cureme', '0003_alter_appointment_options_alter_heartrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cureme.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cureme.patient')),
            ],
            options={
                'db_table': 'cureme_doctor_patients',
            },
        ),
    ]
